### ISSUE TITLE
Rename source.name to source.label?

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#10]
@mjhenkes pointed out that for sources we use _name_ but links and suggestions use _label_ for effectively the same thing. I propose we rename source.name to source.label for API consistency.

👍 👎  requested from @jmandel & @isaacvetter before I start implementing this change

**Comment by kpshek** [comment]
In addition to renaming source.name to source.label, I also want to add an explicit section that says "Each Source is described by the following attributes.", similar to what we have for Suggestions and Links

**Comment by isaacvetter** [comment]
:thumbsup: Makes sense.

**Comment by jmandel** [comment]
Yes, I think consistency is a win here!

**Comment by kpshek** [comment]
Fixed in the api at https://github.com/cds-hooks/api/commit/3efbc6ae0e99be194ab025f4f546e02acfba7e74
