### ISSUE TITLE
Remove apostrophe in CDS overview diagram

### ISSUE THREAD

**Issue by Pyrrh** [cds-hooks/docs#108]
need to update "it's" to 'its' in this diagram & republish: 
https://github.com/cds-hooks/docs/blob/master/source/images/overview.png

**Comment by brettmarquard** [comment]
Fixed in PR105

**Comment by kpshek** [comment]
Thanks for the issue @Pyrrh! I went ahead and fixed this on PR #111 (since #105 was abandoned).
