### ISSUE TITLE
Add source for png images

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/docs#110]
How are the `.png` images like `source/images/overview.png` maintained? It would be good to include an svg source in this repo so that users can propose edits directly.

**Comment by brettmarquard** [comment]
Did you create the originals? I am a little embarrassed to admit I updated the images a bit using powerpoint.

**Comment by jmandel** [comment]
I created the originals in svg (see https://raw.githubusercontent.com/wiki/cds-hooks/cds-hooks/images/overview-with-decisions.svg). No cause for embarrassment; the current diagrams look good! Just add your PowerPoint to the repo, or import into Google docs (or make an svg) and link to that.. the goal is just to make sure nobody needs to recreated this from scratch to propose a change.

**Comment by brettmarquard** [comment]
Thanks - added in PR #111

**Comment by kpshek** [comment]
Fixed & merged in PR #111.

Check out https://github.com/cds-hooks/docs/tree/master/diagrams for the source diagram
