### ISSUE TITLE
Move CDS Service request parameters patient and encounter to Context

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#119]
Today, the `patient` and `encounter` parameters are defined in the request to the CDS Service. However, what if we have hooks that:

- Do not have a patient in context. For instance, consider a hook `ehr-launch` that is invoked as soon as the user launches the EHR application.

- Have more than one patient in context. For instance, consider a hook `patientlist-view` that is invoked when the user is viewing their patient list.

In both of these scenarios, that current location of our `patient` and `encounter` parameters is not optimal. Either the parameters are `null` (or not set) or they are not set and instead superseded by a more appropriate parameter in the `context` in the CDS Service request.

The proposal to address this would be to remove `patient` and `encounter` from the CDS Service request and instead place these as parameters in the `context` object when appropriate for a given hook. For the three hooks we've defined and implemented today (`patient-view`, `medication-prescribe`, `order-review`), they would all include `patient` and `encounter`.

In offline discussion with @brynrhodes and @isaacvetter, we all agreed this would be a good change to make for 1.0. While this is technically a breaking change, it will serve us better down the road as we start implementing and supporting new hooks in which there is no patient or no single patient in context. Additionally, this is a minor change as we're simply just moving where in the JSON structure these parameters are read.

Given that it is a breaking change, we would appreciate thoughts from the rest of the community.

**Comment by kensaku-kawamoto** [comment]
I think it's a reasonable change and a good idea.

**Comment by grahamegrieve** [comment]
so to be clear, this is a significant change because you are replacing the ids of the these things with the whole resource. That's.... potentially significant. I'm making sure that this is clear

I'm in favor of this change. It works for my existing use cases, that include some where patient and encounter are not in context, and some where they are

**Comment by kpshek** [comment]
> so to be clear, this is a significant change because you are replacing the ids of the these things with the whole resource. That's.... potentially significant. I'm making sure that this is clear

That is **not** what I'm proposing. Both the `patient` and `encounter` parameters would continue to just be the ids still.

**Comment by brynrhodes** [comment]
> so to be clear, this is a significant change because you are replacing the ids of the these things with the whole resource. That's.... potentially significant. I'm making sure that this is clear

It would depend on the hook though, right? A hook could define the `patient` parameter as the resource, or it could define it as a `patientId` parameter. I see that as another advantage of this approach, it would be up to the hook to specify what it would actually provide.

**Comment by kpshek** [comment]
Correct, each hook defines the `context` object as it sees fit. However, we're not proposing we start sending the full Patient and Encounter resource in place of the ids we're sending today. For the 3 hooks we've defined today, it would continue to be ids.

**Comment by grahamegrieve** [comment]
> That is not what I'm proposing

but context is an array of resources....

**Comment by jmandel** [comment]
Not if we land#39 appropriately -- which I think is increasingly critical if we make sense the change proposed here. Doing this change without #39 would be very messy.

**Comment by grahamegrieve** [comment]
really? that's not evident to me from the description of #39

**Comment by kpshek** [comment]
> but context is an array of resources....

Today, we document it as "Hook-specific contextual data that the CDS service will need". #39 is going to clearly define how a new hook is defined. Related to this, `context` is an object with keys/values specific to each individual hook. From an earlier comment from me on #39:

> From [some Zulip discussion on this issue](https://chat.fhir.org/#narrow/stream/cds-hooks/subject/docs.20.2F.20Issue.20.2336.20Context.20as.20a.20list.20of.20FHIR.20Resources), we're proposing that context is always a JSON object. Furthermore, context is defined per hook which each hook defining the individual keys and values (both the JSON value type and the content) within the context JSON object.

**Comment by WWie** [comment]
I am in favor of that change. The patient and encounter Ids are indeed context but not always part of the active context. Putting them in the context object as optional makes sense. And putting more work into defining what context objects are and where they are well-defined vs. customizable will go a long way making this framework more robust.

We are looking into various scenarios where we would want to invoke a hook where the context would be a "class of patients", e.g. "Any patient with diagnosis X , Y or Z and age between 50 and 75". Having to still put a value into a high-level attribute like patient or encounter would make it a bit awkward to use. So would having to ignore a high-level parameter in the hook call.

**Comment by robs16** [comment]
How does this interact with the prefetch requirements for a Patient.id replacement? I mean if you are going down the road of these items being part of the context (and I think that might be reasonable), it seems that the prefetch replacements need to be defined somewhat dynamically.

**Comment by kpshek** [comment]
This issue has been addressed by PR #109 and #153
