### ISSUE TITLE
Remove CORS from the specification and into a new developer guidance page

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#125]
The CDS Hooks specification doesn't need to contain information on CORS; rather, we should move this into some new developer guidance page.

**Comment by isaacvetter** [comment]
Instead of creating a "Developer Guidance" page on the website, I moved the CORS section from the spec into the existing [Security Model FAQ](https://github.com/cds-hooks/docs/wiki/Security-Model-FAQ) wiki page in PR #170
