### ISSUE TITLE
How to support audit trail for no action?

### ISSUE THREAD

**Issue by vadi2** [cds-hooks/docs#164]
Let's say a hook is called, and no action needs to be taken, but the EHR needs to know the decisions the CDS service took for auditing purposes. We thus have a situation where the user should not be bothered with any information but the EHR needs to receive information for auditing purposes.

I recall there were discussions around whenever every card must be displayed to the user, and while I can't find the outcome of that right now, I think the consensus was that every card does need to be displayed to the user. How can the CDS service then return audit information for the "no action" usecase without spamming the user?

**Comment by kpshek** [comment]
Do you have a particular use case (concrete data you want to write back)? My opinion on this depends upon the scenario. 😄 

For instance, if the data you need to write back is available a FHIR resource, then it seems reasonable for the CDS Service to simply make a FHIR write call to push this type of data.

**Comment by vadi2** [comment]
Yes, that would work actually! I imagine the audit information would go into an AuditEvent just fine. Thanks for the quick response.

**Comment by kpshek** [comment]
No problem! Glad it was that easy!
