### ISSUE TITLE
Prefetch query restrictions need

### ISSUE THREAD

**Issue by brynrhodes** [cds-hooks/docs#173]
The example used to illustrate prefetch query restrictions [here](http://cds-hooks.org/specification/1.0/#prefetch-query-restrictions) needs to be updated to reflect changes to context parameterization.

Specifically, it still says `patient={{Patient}}`, it should now be `patient={{context.patientId}}`.

The entire spec should be reviewed for this change.

**Comment by isaacvetter** [comment]
Is this a duplicate of #151? 

Note that @kpshek addresses #151 in PR #181 and @brynrhodes addressed this issue in PR #183.

**Comment by kpshek** [comment]
I agree @isaacvetter - I think this is a duplicate and has already been addressed.
