### ISSUE TITLE
Consistent documentation of types

### ISSUE THREAD

**Issue by brynrhodes** [cds-hooks/docs#177]
For tables that describe types in the spec, the name of the type is always included as the first part of the Description. These should be broken out into their own column, and we should clearly identify a list of types that are possible, starting with:

string
number
url
object
array
FHIR resource

Also, the type of the "hook" element of the Discovery and Request should be just "string", not "string or url".

**Comment by kpshek** [comment]
Closed with the merge of PR #183.
