### ISSUE TITLE
JWS RFC identifier is incorrect in the Trusting EHRs section of the spec

### ISSUE THREAD

**Issue by isaacvetter** [cds-hooks/docs#189]
@yashaskram pointed out that PR #186 included a typo that made the reference to the JSON Web Signature IETF RFC incorrect, despite the anchors hypertext reference being correct.

Specifically, this markdown:
><pre>as defined by [rfc<b>7517</b> 4.1.2](https://tools.ietf.org/html/rfc<b>7515</b>#section-4.1.2).</pre>

[7517](https://tools.ietf.org/html/rfc7517) is the JWK rfc, [7515](https://tools.ietf.org/html/rfc7515) is the JWS rfc.

**Comment by kpshek** [comment]
This was fixed in #190 and merged in d4d9cd5c7a2bb21b872ab1cca025f220d7c24ddd
