### ISSUE TITLE
Clarify source is the primary source of guidance

### ISSUE THREAD

**Issue by robs16** [cds-hooks/docs#19]
The source within the Card structure is defined as:

> the source of the information displayed on this card.

This is ambiguous as there are likely multiple sources which could be related to a card. This could refer to:
* The service providing the card
* The primary source of guidance (ex Choosing Wisely)
* Secondary sources such as research citations

We believe that the source referenced in the Card structure should be the primary source of guidance and the documentation should clearly state this.

**Comment by jmandel** [comment]
I agree that this field should be used for the primary source of guidance. (In general, this can be a slippery concept; services might populate it more or less strictly.)

**Comment by robcz** [comment]
While clarifying, there appears to be a bit of clean-up in synchronizing the documentation with the example response.  The documentation has source typed as string vs. object.  Additionally, the example has a "name" property of source while the documentation references that property as "label".

**Comment by kpshek** [comment]
I opened pull request #30 to address the issues raised here. Can you all take a look at let me know if it looks good?

@robcz - Thanks for pointing out the discrepancy on the source type (string vs object) documentation typo. You mentioned that `name` was referenced in the source examples instead of `label`. I think I fixed all of those in 927d5a8. Can you let me know if I missed any?

**Comment by robs16** [comment]
For clarity in the examples, you might want to use something a bit more real as it helps to illustrate intended use. Perhaps from http://www.choosingwisely.org/clinician-lists/

**Comment by kpshek** [comment]
> For clarity in the examples, you might want to use something a bit more real as it helps to illustrate intended use. Perhaps from http://www.choosingwisely.org/clinician-lists/

Agreed @robs16! I've logged #32 which is broader than your suggestion (but includes it) to add more clinically relevant examples to our documentation.
