### ISSUE TITLE
Clarify the update action type

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#196]
I do not think there is enough clarity around the `update` action type. For instance, when a CDS Service wants to suggestion the user add an additional attribute to a resource, should the resource be the complete FHIR resource (with the additional attribute) or just the single additional attribute?

The same questions can be asked when attributes about the FHIR resource need to be modified or removed entirely.

**Comment by AlexTatiyants** [comment]
Not requiring a complete resource for updates makes a lot of sense to me. For more complex resources (like orders), it's unlikely that the CDS service will have all of the details necessary to fully update the resource properly. The EMR is in the best position to "merge" changes proposed by the CDS service with the existing resource.

**Comment by kpshek** [comment]
In addition to what @isaacvetter said, we can evaluate a FHIR PATCH action in a future version of the specification.
