### ISSUE TITLE
Add a list of CDS Providers to "Docs > Community"

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#2]
Copying over from cds-hooks/cds-hooks#14:

@jmandel said:

> Should include:
> http://cds.medapptech.com
> http://hooks.fhir.me:8082

**Comment by kpshek** [comment]
@jmandel - Are you still in favor of this?

I don't have particularly strong feelings about a list of CDS services. If we want these, I'd prefer to put them on a Wiki page rather than the main documentation so that it can be a living document with the ability for anyone to easily add/update their URL.

**Comment by jmandel** [comment]
I think a wiki page (linked from the docs) is a great idea. Gives people some things to try out in the test harness, and can also include links to source code for open-source hooks. Basically, an equivalent of http://wiki.hl7.org/index.php?title=Publicly_Available_FHIR_Servers_for_testing

**Comment by kpshek** [comment]
@jmandel - Sounds good. Take a look at pull request #31 and [this new wiki page](https://github.com/cds-hooks/docs/wiki/CDS-Services-for-testing) and let me know what you think.

**Comment by jmandel** [comment]
Great -- thanks @kpshek .( I added a tiny bit of formatting.)

**Comment by jmandel** [comment]
Great -- thanks @kpshek . (I added a tiny bit of formatting.)
