### ISSUE TITLE
Ballot comment from HLN Consulting regarding card.detail Markdown and hook definition

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#203]
Daryl Chertcoff, Project Manager at HLN Consulting, LLC made an Affirmative vote for CDS Hooks in the May 2018 ballot. Included with his ballot was the following comment:

> 1) If possible, for detail returned in Card attributes, suggest requiring that GitHub Flavored Markdown support table extensions, as per https://github.github.com/gfm/#tables-extension
> 
> 2) Suggest more guidance in the specification about how to define Hooks unambiguously with respect to when CDS Services that subscribe to the hook are actually. For example, in the Workflow section of the new-hook-template, how does does the author unambiguously define the appropriate screen & workflow upon which CDS services that subscribe to the hook are invoked? Can the role of the EHR user be specified as well? (E.g. - A hook is created for an administrative user, but not clinicians)

**Comment by kpshek** [comment]
> 1. If possible, for detail returned in Card attributes, suggest requiring that GitHub Flavored Markdown support table extensions, as per https://github.github.com/gfm/#tables-extension

The card `details` field is already documented today as supporting GitHub Flavored Markdown and thereby, tables are supported as that is part of GFM. Also see #319 which relates to our support of GFM.

Regarding your second comment on defining hooks unambiguously for a particular workflow as well as role specific hooks, I'd break this down into two questions:

_How do we unambiguously define hooks for a particular workflow?_

Other than specifying as clearly as possible the workflow the hook is to be invoked on, I don't know what else we can do here in the specification. I think our eventual hook maturity model (see #195) will help with this (via encouraging multiple implementations of a hook across vendors).

_What about hooks defined for a particular role?_

Right now, this feels like more of a filtering the CDS Service is doing (to only return CDS when called by a user in a particular role) rather than part of the hook definition. Perhaps concrete examples would help be understand this use case better.

**Comment by isaacvetter** [comment]
>Suggest more guidance in the specification about how to define Hooks unambiguously with respect to when CDS Services that subscribe to the hook are actually. For example, in the Workflow section of the new-hook-template, how does does the author unambiguously define the appropriate screen & workflow upon which CDS services that subscribe to the hook are invoked? Can the role of the EHR user be specified as well? (E.g. - A hook is created for an administrative user, but not clinicians)

Issue #195 describes a similar problem and was resolved in PR #402 by defining a full hook maturity model, as well as further specifying and strengthening the documentation requirements for hooks. Notably, including a requirement for a (workflow description](https://cds-hooks.org/specification/1.0/#workflow).

Closing as resolved.
