### ISSUE TITLE
What does a 'success' card represent?

### ISSUE THREAD

**Issue by robs16** [cds-hooks/docs#24]
The documentation does not make it clear what a card with an indicator of 'success' signifies. Does it signify that CDS was executed and there are no suggestions/warnings/information/etc? Or does it just mean that the CDS ran (i.e. it should be returned with basically every response and probably simply ignored by the consumer). What is the proper way to tell the consuming system that there were no suggestions/warnings/information? Note that this may be required and include extra information for supporting PAMA/etc.

**Comment by kpshek** [comment]
@jmandel - Do you have thoughts on the `success` indicator since you came up with our original indicators (`success`, `info`, `warning`, and `hard-stop`)? I admit that I don't know when a CDS service would use that particular indicator value.

@robs16 - I logged #29 several days ago to address documenting what should be returned from the CDS service in the case that no decision support is required. Let's continue the discussion on that question over there.

**Comment by jmandel** [comment]
When I was putting this together, I just grabbed terms from [bootstrap](http://getbootstrap.com/components/#btn-dropdowns-single) to have something quick to work with. So the short answer is: we might strip this out altogether.

If I had to justify, I guess the best I could do would be: "a card communicating the fact that a user's choice 'looks good' to the CDS system".

  -J

**Comment by kpshek** [comment]
Thanks @jmandel!

Based upon this, my opinion is we remove 'success' as an indicator option. While there is a semantic difference between "your choice looks good" and "there is no decision support", I'm not sure this is needed. When I think about Cerner's proprietary rule engine and the 3rd party rules we have incorporated today, none of them offer a "your choice looks good" message to the user (at least none that I am aware of).

I'd love to hear other thoughts on this.

**Comment by jmandel** [comment]
If nobody says they want it, I'm A-OK with stripping it!

**Comment by robs16** [comment]
In my opinion, there is a need for something like 'success' though not necessarily implemented as a card. #29 suggests an empty set of cards, but you cant get to a solution for #13 without some data in the response (not saying this must be a card).

**Comment by brynrhodes** [comment]
I agree with the ability to represent "success", possibly even with a message, though that message may not be given to the user in that case. For example, we have decision support right now where we want to say "we looked at the meds you provided and they did not have any opioids". The user might not care, but it might be useful for retrospective analysis of how the service was used.

**Comment by jmandel** [comment]
We should be clear to separate out the issue of saying "the CDS Service ran successfully", from a user-facing card indicating a happy message. This issue is about the latter. If we want to contemplate the former, let's capture it in a separate issue?

**Comment by kpshek** [comment]
Well put @jmandel.

#13 deals with something close to recording the fact that the CDS Service ran successfully and this needs to be recorded somehow. Let's continue the discussion with that use case there.

@robs16 - Do you have a need at Stanson Health for showing the user a card that informs them everything is good?

I've added this issue to our list of notable issues for Connectathon participants to weigh in on. It would be great to hear from other CDS Service providers to get their thoughts here.

**Comment by robs16** [comment]
I don't see a particular need to represent 'success' in a user-facing card.

**Comment by peremarshall** [comment]
I think there are times when an "everything is okay" message is good to convey, but the "info" card should be sufficient for this purpose.

**Comment by kpshek** [comment]
At the Madrid Connectathon this past weekend (2017-05-07), a large group of us participating in the CDS Hooks track discussed this issue in an offline discussion. This group of ~12 represented a broad set of stakeholders, from multiple EHR vendors, several CDS Service providers, and a healthcare organization. What follows is the summary of our discussion and the consensus of the group.

We all agreed that the `success` indicator value should be removed as no one could articulate a use case that warrants its inclusion. Additionally, we all agreed that cards should be user facing constructs.

> What is the proper way to tell the consuming system that there were no suggestions/warnings/information? Note that this may be required and include extra information for supporting PAMA/etc.

Regarding this use case, we acknowledge this needs to be addressed. See #48 regarding discussion around a proposal for this.
