### ISSUE TITLE
What Markdown flavor and/or restrictions should be applied?

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#33]
In discussion with @brynrhodes and @isaacvetter, we had some questions that we should answer in the spec/documentation:

**Markdown Support**
Is Markdown required or an optional feature that EHRs can support? If Markdown is optional, it would be nice for EHRs to advertise their support for it so that CDS Services can return cards accordingly.

**Markdown Flavor**
What flavor of Markdown should CDS Hooks support? Eg, [CommonMark](http://commonmark.org/)? [Github Flavored Markdown](https://github.github.com/gfm/)? etc.

**Risks with Embedded HTML in Markdown**
Markdown allows for any embedded HTML. Should this be allowed? If so, we need to document how EHRs must mitigate against risks of cards that now contain executable code (JS) or conflicts with CSS classes/names.

Risks with embedded HTML is actually no different than risks posed by embedding SMART apps in an EHR. However, we should probably call out good practices (like usage of iframes).

A potential difference between integrating SMART apps and CDS cards into the EHR is the level of integration we expect with CDS cards. The intention is that since the majority of a CDS card is structured data rather than UX (or entirely if there is no embedded HTML), then the rendering of the card should be close or indistinguishable from the native EHR.

Another point of consideration is that allowing for embedded HTML in the Markdown starts to veer CDS cards in the direction of mini SMART apps.

And finally, another option could be allowing for embedded HTML but only a subset of HTML functionality/tags (a whitelist). This would offer CDS cards the ability to style themselves somewhat but perhaps disallow them from incorporating app-like functionality.

Thoughts & discussions from the community is welcome!

**Comment by jmandel** [comment]
I think Markdown is optional, and we should do our best to "pick one". We need to be quite careful about embedded HTML, but I think we need a way to reference at last images (possibly with a restriction to only allow inline base64 data-url images, if we want to avoid calls out to an external server) and tables (I know Markdown enables tables without HTML, but it's kind of a pain IMO). 

There's some relevant discussion at:
https://www.hl7.org/fhir/narrative.html#2.4.0
https://www.hl7.org/fhir/security.html#narrative

**Comment by robs16** [comment]
I'm of the opinion that it should be a strict subset of markdown (we have implemented headings, numbered lists, unordered lists, and links). The EHR in most cases would do actual formatting and styling (after all you cannot assume this is displayed in a browser - and it is highly likely that there are space constraints), while what they need is the structure of the text and links. The alternative of plain text doesn't work well in practice. For real cards provided via hooks today, I have primary statements, secondary statements (long), and supporting evidence (citations with links), and a few other items. All of this is pushed into the detail as there is no better place for it.  An alternative might be to move it all to the smart app, but that would mean suggestions are of little use in a real CDS application.

**Comment by jmandel** [comment]
> For real cards provided via hooks today, I have primary statements, secondary statements (long), and supporting evidence (citations with links), and a few other items

This is great feedback, thanks!

**Comment by seanmsmith23** [comment]
As much as we'd love to use all of HTML as a CDS-service provider, I think it makes the most sense that cards have a standardized feel so that the provider becomes familiar/comfortable with what they are seeing and why (which I think everyone would benefit from).

I don't have strong feelings about exactly what flavor of Markdown to use. Just so long as we get more flexibility than plaintext.

**Comment by gotdan** [comment]
Hmm, I wonder if we could borrow slack's card format? They defined a straightforward json schema that includes a subset of markdown, as well as a way to incorporate "attachments" such as images, "fields" of data, and buttons: https://api.slack.com/docs/messages#composing_messages . 

Also, down the road, we could also potentially use parts of their in-card interactive messages framework to support user feedback mechanisms beyond suggestion buttons and links: https://api.slack.com/interactive-messages .

**Comment by vadi2** [comment]
Grahame is heavily favouring CommonMark btw.

**Comment by grahamegrieve** [comment]
I do now favor CommonMark if we're talking about markup variants.

**Comment by kpshek** [comment]
The only downside I've heard from implementors with CommonMark is the lack of support for tables in Markdown, thereby requiring HTML tables. If we decide to disallow HTML for the time being, this would prevent tables from being used altogether.

**Comment by isaacvetter** [comment]
It's clear that we want to provide some capability for a cds service to specify content markdown. 

>Markdown allows for any embedded HTML. Should this be allowed?

I think that the general consensus here is no, raw html shouldn't be allowed. Looking at FHIR's experience with narrative, supporting html fragments looks messy. A safe markup language is the best choice.

>I think Markdown is optional

@jmandel - optional for whom? I imagine that plain text is a subset of any markdown flavor, so it's optional for cds services. Are you also suggesting that it's optional for the EHR? If so, how would that work? 

>CommonMark ... lack[s] support for tables

I'd guess that this is a big deal, but it's the cds services whose experience matters. @seanmsmith23, @robs16, @euvitudo, others? Is table support a hard requirement?

**Comment by jmandel** [comment]
I'm saying some EHR might decide not to render markdown nicely. I think it would be a poor choice, but I don't know that we have to militate against it.

**Comment by robs16** [comment]
@isaacvetter - So far tables have not been a hard requirement for our service.

**Comment by euvitudo** [comment]
@isaacvetter - The opioid use case used a table to display the list or prescribed meds.

**Comment by kpshek** [comment]
For those interested in following along with FHIR's work to land on a standard flavor of Markdown, follow [gForge #13376](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13376)

**Comment by seanmsmith23** [comment]
Tables are not a hard requirement for us. Probably mostly just need to be
able to create some emphasis for sub-headers, bulleted lists, etc...

**Comment by kpshek** [comment]
> Hmm, I wonder if we could borrow slack's card format?

@gotdan - Thanks for pointing out the Slack message format! I use Slack everyday but never have looked at their API. Its clear they have designed an API that allows for rich messages from 3rd party integrations.

One of the drawbacks of using designing a bespoke message format (like Slack's) is that EHR implementors will need to write parsers for this format. This is an advantage of Markdown -- the ability to use an OSS parser.

**Comment by isaacvetter** [comment]
Overall, styling should be controlled by the EHR. This is important to provide a consistent user experience. Yet, some amount of minimal markup is important for the CDS service to provide to enable a clinician to rapidly understand data visually.  Visual representation of data is important to translate data to users -- it seems important that the markup functionality support tables. Further, a card's detail must be treated as non-executable code (not html, javascript, etc), for security reasons. 

Considered approaches:
* [CommonMark](http://spec.commonmark.org/0.5/) without html support - doesn't support tables.
* FHIR-defined xhtml data type - [xhtml](https://www.hl7.org/fhir/narrative.html#xhtml)
* [GitHub flavored markdown](https://github.github.com/gfm/#what-is-github-flavored-markdown-), which is CommonMark+tables, no html, 

The joint goals of data visualization -- including tables, and security -- outlawing html, land us squarely on GitHub Flavored markdown. 

I'm going to write up a PR for GitHub Flavored markdown to be in the spec as the support markup method in CDS Hooks responses' detail element.
