### ISSUE TITLE
Add CDS Service logo/icon?

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#34]
It has become apparent that CDS Service vendors/developers want to include a logo or image of some sort in their cards. Today, these developers are doing this with an image tag in the Markdown of the card details. This is fraught with UX issues as the CDS Service developer doesn't know how big to make the image since how it is rendered varies by EHR.

Perhaps we should add first-class support for a logo/icon either in the card itself (via a first-class attribute) or in the CDS service definition in the Discovery endpoint.

We should be prescriptive on the size and format of the logo/icon. Additionally, we should be clear if this is a logo or an icon (there is a difference from a UX perspective).

I'd like to explore first if we can put this in the Discovery endpoint for each service rather than an attribute on the card.

**Comment by jmandel** [comment]
I think an explicit field for log, with prescriptions on size, would be lovely.

I'd be wary of making the Discovery endpoint the *only* place where this info lives, because I want to enable the possibility of aggregator services that might present a unified discovery endpoint for services in different groups or from different publishers. (We could say: this happens with separate discover endpoints for each group/publisher, but there are advantages to having this happen in one place, unless we want to design a meta-discovery protocol :p)

If we need an attribute in the cards, I'd rather avoid the complexity of defaulting-to-a-discovery-supplied-logo.

**Comment by kpshek** [comment]
I've attempted to lay out the various options and their impact/considerations:

**Defining in Discovery**

- 👍 Allows the EHR to display the image in any tool used by users configuring the CDS Services
- 👍 Allows the EHR to cache images upfront / early (no need for a just-in-time cache)
- 👎 Requires EHRs to cache images and apply them to each card
- 👎 Hampers aggregation services if they intended to display a unique image based upon the underlying service they wrapped/aggregated.
- ❓Should the image be defined for the discovery endpoint (for all services) or per service? Flexibility at the cost of added complexity.

**Defining in each card**

- 👍 Allows the all services (including aggregation services) to define whatever image they want (perhaps they want to provide a tailored image for each card)
- 👍 Removes the burden of the EHR from storing the images (if they don't want to cache them)
- 👎 EHR has no image to display in a tool used by users configuring CDS Services
- 👎 EHRs must implement a just-in-time / progressive cache (if they are caching images at all)

**Defined in both Discovery and each card**

- Image defined in card would override image defined in Discovery
- Most complex of the three options
- Addresses all 👎 of just defining in Discovery
- Addresses 👎 of EHR not having an image for a Discovery tool

---

I'm going to solicit feedback from our CDS Service participants at the Connectathon this weekend. I don't know of anyone who represents an aggregation CDS Service. I wonder how many of these are/will exist.

After writing up all of these options and thinking through each, I'm now leaning towards what I believe to be the most simple approach -- defining this in each card.

**Comment by peremarshall** [comment]
For consistency, I think it belongs in the JSON for each card. That's where all the rest of the content is sourced. As for the downsides of that approach...

* I don't think the people doing the configuration of the services need a logo.
* All of the other content on the card can't be cached upfront, including the "source" attribution which is most closely related to this logo asset.

I think having it in both would lead to confusion.

**Comment by isaacvetter** [comment]
Hey Everybody - a couple of points:

1) This is a nice feature to support. I don't think it's vital to a 1.0 release.
2) I read Apple's App Icon UX guidelines (per @kpshek's [link](https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/)). They're solid UX guidelines, but don't help us figure out what should be in the spec.

I think that the primary questions are: 
* What size and shape should the icon be?
* Do we need to support multiple icons?

Continuing the analogy to Apple, here's the [list of sizes](https://developer.apple.com/library/content/qa/qa1686/_index.html) that they require. (Note that they're all square). 

@gotdan pointed to [slack's card format](https://api.slack.com/docs/messages#composing_messages) as an analogy in #33, but I don't think they're supporting dynamic icons.

**I'm going to propose that cards can define a small square icon of 40x40px (apple spotlight size) and a large icon of 120x120px. The card should point to a url.**

Thoughts?

**Comment by kpshek** [comment]
@isaacvetter - Thanks for trying to reign in the discussion to a concrete proposal. I've reached out to some of our UX designers to get their feedback on dimensions as well as specifics such as alpha channels. I'll reply back here with their feedback. Feedback from others is also welcome!

I was hoping we could define just a single optional attribute for this, rather than having multiple attributes for varying sizes. But, I was waiting to hear back from my UX designer colleagues.
