### ISSUE TITLE
Add R4 resources to existing tasks

### ISSUE THREAD

**Issue by lmckenzi** [cds-hooks/docs#397]
medication-prescription.medications: same as STU3

order-review.orders: R4 - FHIR Bundle of MedicationRequest, ServiceRequest, NutritionOrder with draft status

(Note R4 *might* include VisionPrescription too, but that's supposed to be subsumed by DeviceRequest - see https://github.com/cds-hooks/docs/issues/396)

**Comment by isaacvetter** [comment]
Thanks, @lmckenzi !

I'm going to leave this open and mark is as deferred until R4 is final.

**Comment by isaacvetter** [comment]
I'm pretty sure that this issue is resolved. R4 is published and our hooks document R4 resources.
