### ISSUE TITLE
Switch from "name" to "title" in service discovery for consistency with FHIR's use of name and title

### ISSUE THREAD

**Issue by isaacvetter** [cds-hooks/docs#40]
In discussion with @brynrhodes and @kpshek regarding aligning Clinical Reasoning and CDS Hooks, Bryn pointed out that FHIR consistently uses an attribute "name" for a "computer friendly name" and "title" for a "human friendly name"; yet, CDS Hooks is currently using "name" as a human friendly string.

We should change this to avoid confusion for FHIR developers.

CDS Hooks uses the term "name", which should be "title" in the service discovery response.

**Comment by kpshek** [comment]
This change was made by @isaacvetter in 48616d2 and merged to master in b83c475 but this issue didn't get closed. Closing now.
