### ISSUE TITLE
The term EHR is inaccurate

### ISSUE THREAD

**Issue by isaacvetter** [cds-hooks/docs#407]
[_Updated proposed explanatory sentence to incorporate Lloyd and Guilherme's feedback._]
In the spec, we've consciously chosen to use the term "EHR" to illustrate a primary use-case of CDS Hooks. 

For some users of CDS Hooks, this minimizes their role and suggests that CDS Hooks is not applicable -- even when it is!

We should define a new term, such as "_CDS Hooks Client_" and add an explanatory sentence, such as:
>The CDS Hooks specification uses the term CDS client to generically refer to the clinical workflow system, such as an EHR, in which a CDS services returned cards are displayed or processed.  

and remove other references to "EHR".

Isaac

**Comment by kpshek** [comment]
I am strongly in favor of this change. While we are extremely reluctant to introduce any new scope into the impending 1.0 release, I think this change would be an easy and welcome addition to 1.0. It doesn't introduce any new features of implementers and simply clarifies the actor we've had trouble describing (narrowly using EHR).

**Comment by lmckenzi** [comment]
It would be good to list EHRs as an example of a client so that readers realize they're one of the targets, but agree that generic terms would be best throughout the spec.  (I've tried to use the term 'client' throughout DaVinci - I'm hoping pharmacy management systems, dental systems and others may come online at some point too :>)

**Comment by kensaku-kawamoto** [comment]
I agree with this.

**Comment by gdelfiol** [comment]
I suggest appending the description above with something like "The CDS Hooks specification uses the term CDS client to generically refer to the clinical workflow system in which a CDS service's returned cards are displayed **or processed**." 

This would cover use cases where a CDS service response is consumed by a backend process and not intended to be displayed to a user (e.g., a population health management system that automatically enrolls a patient into a chronic disease management program).

**Comment by kpshek** [comment]
@isaacvetter - I've pulled this into the 1.0 scope. Let me know if you disagree.
