### ISSUE TITLE
Clarification on example prefetch template

### ISSUE THREAD

**Issue by faizalMo** [cds-hooks/docs#410]
The [spec](https://cds-hooks.org/specification/1.0/#http-request_1) says that the user field in the POST request to a CDS Service would be of the format FHIR resourceType+id, in that case if the service wants the EHR to prefetch user information, the template should really be 

`prefetch: {
         user: '{{user}}'
    }`

as such the example given [here](https://cds-hooks.org/specification/1.0/#example-prefetch-templates) is wrong?

**Comment by mattvarghese** [comment]
Now with the old `/user` moved to `context/userId`, there is still a problem with [this](https://cds-hooks.org/specification/1.0/#example-prefetch-templates) example.
`context/userId` is of the form `Practitioner/{id}`

So this line
`"u": "Practitioner/{{context.userId}}"`
Becomes
`"u": "Practitioner/Practitioner/{id}"`

I would say the context should remove `userId` and have a field `practitionerId` which is just the ID. _Alternatively, we can remove the `Practitioner` prefix from `userId`, but now we have an ID, which is or a type that is not directly obvious and therefore tacky._
