### ISSUE TITLE
Transaction behavior on suggestions

### ISSUE THREAD

**Issue by lmckenzi** [cds-hooks/docs#419]
When returning suggestions back from a decision support service, it's possible that the server can return multiple "create" actions as part of a single suggestion - and that the resources to be created can have references to each other.  As such, the creates (or updates) will need to be processed in a transactional manner.   At present, the CDS Hook specification does not provide any guidance setting this expectation, nor does it provide guidance about how resources are to point to each other.  Suggest adding guidance that states that resource ids must be included in the resource instances to be "created" if there are interdependency issues and that the actions will be processed as a FHIR "transaction" with the full URLs being inferred as the base URL of the CDS client's server.

**Comment by isaacvetter** [comment]
@lmckenzi - this seems perfectly reasonable, are you willing to suggest actual text?

**Comment by lmckenzi** [comment]
When a suggestion contains multiple actions, the actions SHOULD be processed as per FHIR's rules for processing [transactions](https://hl7.org/fhir/http.html#trules).  Specifically, creates happen first, then updates, then deletes.  Also, references between resources in the different actions are resolved as per transaction rules, with the qualifier that the "base URL" for the 'transaction' entries will be the base URL of the CDS client's server.

**Comment by brynrhodes** [comment]
Added tracker in JIRA to support this: https://jira.hl7.org/browse/FHIR-35878
