### ISSUE TITLE
Improve analytics functionality - let cds service know when suggestion is rejected

### ISSUE THREAD

**Issue by isaacvetter** [cds-hooks/docs#42]
In discussion with @brynrhodes and @kpshek regarding aligning Clinical Reasoning and CDS Hooks, one of the topics of discussion was around the ability of the cds service to know when a suggestion was rejected by the end user. 

Currently, our analytics endpoint accepts a uuid when "a button is clicked", as we necessarily complicate the suggestion model, this may not be sufficient to describe the actual suggestion accepted by the user and does not capture a concept of rejection.

This issue is related to, but not necessarily the same as #41. Overall, I think that we need to re-design the analytics endpoint, so that the cds service is able to improve its behavior and so that the end-user has a positive and meaningful experience with the cds.

**Comment by bdoolittle** [comment]
@isaacvetter Issue [#21](https://github.com/cds-hooks/docs/issues/21) was posted a few months ago and addresses this same problem with the analytics endpoint. There is a proposed solution without any discussion around it. Please take a look and see if the proposal fits your needs.

**Comment by isaacvetter** [comment]
Thanks, @bdoolittle !

Closing in favor of @robs16's #21.
