### ISSUE TITLE
Order-review hook has error in documentation of Context

### ISSUE THREAD

**Issue by boxwala** [cds-hooks/docs#427]
The Context section of the order-review hook has an error. Seems like a cut-n-paste leftover from the medication-prescribe hook.

> The set of orders being reviewed for signature on-screen. All FHIR resources in this context MUST be based on the same FHIR version. All FHIR resources in the medications object MUST have a status of draft.

The last sentence does not apply here since there is no medications object in this hook.

**Comment by isaacvetter** [comment]
Ouch! Despite @boxwala telling us about this problem last fall, we still haven't fixed it .... :(

Thank you, @boxwala . Fixing now.
