### ISSUE TITLE
Remove all mentions of specific hooks from the specification

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#436]
Today, the specification references several specific hooks. Eg:

> For example, `medication-prescribe` and `order-review` define context fields containing FHIR resources that represent draft resources.

I think we should add clarifying text to indicate these are examples. For instance:

> For example, imagine a hook `medication-order` that is invoked when a user selects a medication during an order workflow. The context data for this hook would contain draft FHIR resources representing the medications that have been selected for ordering.

The hooks we are referencing today will likely change over time and I don't want the specification (which will be much longer lived) to refer to these outdated hooks.

Thoughts on ensuring this happens before the 1.0 release?

cc @isaacvetter @brynrhodes @brettmarquard

**Comment by brynrhodes** [comment]
Applied in #435

**Comment by kpshek** [comment]
Closing as this was resolved in #435.
