### ISSUE TITLE
How should a CDS Hooks service respond to bad prefetch resource(s)

### ISSUE THREAD

**Issue by euvitudo** [cds-hooks/docs#44]
I added a comment to [Issue #37](https://github.com/cds-hooks/docs/issues/37#issuecomment-299674526) that led me to creating this issue.

There doesn't seem to be any documentation for how a service should respond when an invalid (or more generally, an unexpected) value is provided as a prefetch resource.

**Comment by kpshek** [comment]
Hi @euvitudo, I think is a duplicate of #5. If you agree, do you mind if I close this issue as a duplicate?

**Comment by euvitudo** [comment]
If you think so.

**Comment by kpshek** [comment]
Thanks!
