### ISSUE TITLE
Hook definitions should be organized by maturity

### ISSUE THREAD

**Issue by brynrhodes** [cds-hooks/docs#445]
The "hook catalog" should provide a clear indication of the maturity level of the hooks. One easy way to do that would be to have a folder for each maturity level, and as a hook definition progresses, it is moved through the folders.

**Comment by isaacvetter** [comment]
The hardest part about this is assigning [maturity levels](https://cds-hooks.org/specification/1.0/#hook-maturity-model) to our existing hooks. 
@brynrhodes suggests:
* patient-view - 4
* medication-prescribe - 2
* order-review - 1

Do others have feedback on these levels?

**Comment by gravitypersists** [comment]
Doesn't this contradict https://github.com/cds-hooks/docs/issues/436 ?
