### ISSUE TITLE
Create medication-sign and medication-select hooks

### ISSUE THREAD

**Issue by brynrhodes** [cds-hooks/docs#460]
If the direction for the ordering hooks is to create order-select and order-sign hooks and deprecate the order-review hook, the medication-prescribe hook should be deprecated as well in favor of medication-select and medication-sign hooks that are specifically defined as subsets of order-select and order-sign, respectively.

**Comment by isaacvetter** [comment]
related #433

**Comment by brynrhodes** [comment]
After discussion on the CDS WG call on 1/30, consensus was that there was little value in having medication-sign and medication-select as subsets of order-sign and order-select, since most of the selectivity would not be around whether the order was a medication, but rather whether the order was a particular kind of medication. Based on that, I think it makes sense to withdraw these proposed hooks.
