### ISSUE TITLE
Can `order-select` be triggered multiple times during the ordering workflow?

### ISSUE THREAD

**Issue by isaacvetter** [cds-hooks/docs#468]
This distinction is unclear to me -- is it proposing that clinician-supplied details like dosing would not be passed along with this hook? I'm concerned that we're deprecating a simple model (an in-progress hook that re-fires any time an in-progress order changes) in favor of a complex model (https://github.com/cds-hooks/docs/issues/418) **but we've only introducing support for one step* of the complex model.

This strikes me as a net *reduction in functionality without simplifying* the problem.

it is possible I have misunderstood the intention of this hook, in which case it would be good to clarify here and in the definition.

_Originally posted by @jmandel in https://github.com/cds-hooks/docs/pull/428_

**Comment by mattvarghese** [comment]
@jmandel, do we need to keep this issue open, since @isaacvetter made the change you requested in #428?

**Comment by jmandel** [comment]
Don't see why! Closing.
