### ISSUE TITLE
Clarification on terms of use for CDS Hooks Logo

### ISSUE THREAD

**Issue by mattvarghese** [cds-hooks/docs#475]
I'm planning to include CDS Hooks logo (docs/images/logo-square.png) in a software distribution. 
Is the logo covered by the same Apache License 2.0 in the LICENSE file in this repository, or is there a different set of license/copyright terms and conditions I have to adhere to to use CDS Hooks Logo in my software distribution?

**Comment by mattvarghese** [comment]
Also, given issue #474, can you clarify if the Logo falls under 
* Apache License 2.0 in the LICENSE file here
or under
* Creative Commons Attribution 4.0 International License, at the footer of https://cds-hooks.org?

**Comment by jmandel** [comment]
The logo is trademarked to Boston Children's Hospital -- and our intention is to make it available for use in the CDS Hooks project and apps/services that support CDS Hooks. Would it help to have language similar to what's on the https://www.hl7.org/fhir/license.html about the FHIR logo?

**Comment by mattvarghese** [comment]
* @jmandel: Yes, agree, it would be nice to have trademark, copyright and licensing terms of use called out somewhere **on the website** and not just in the GitHub repository. Like FHIR and FHIR logo, it would be nice if this is done for CDS Hooks and CDS Hooks logo. 
* This question arose because the README sounded like logo would fall under Apache license given it is content of this repository that is not Markdown, but legal folks would prefer more clear terms of use. 
>All Markdown content in this repository is licensed under the Creative Commons Attribution 4.0 International License.
>Unless otherwise noted, the contents of this repository are licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
* I talked to @isaacvetter. He thinks the logo ownership was transferred to HL7, but said @kpshek might know details.
* Isaac also asked, should the term and logo be under Apache License, or should it be part of the website / integration, and therefore under the CCA4IL like the rest of the web site.

**Comment by jmandel** [comment]
http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4806:kghju4.3.1 is the relevant trademark info -- let's aim to work with Boston Children's Hospital to craft language for inclusion in the spec. This is all in-flight, obviously, but I wouldn't let that stop you from using the logo to refer to the specification from your own project in the time being!

**Comment by mattvarghese** [comment]
@jmandel, that search expired. Can you list your search keywords / how you looked it up? 
Also, is CDS Hooks a registered trademark? &reg; symbol? 

Would you have some idea of what an example attribution notice should look like? Is the below good enough? 

> **CDS Hooks&reg;** and **<img src="https://cds-hooks.hl7.org/images/logo-square.png" alt="the CDS Hooks logo" title="the CDS Hooks logo" width="24px" height="24px" />**&reg; are trademarks of **HL7** and **Boston Children's Hospital**, copyrighted and licensed under a Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/) as specified at https://cds-hooks.hl7.org/

**Comment by jmandel** [comment]
D'oh. So much for links :-) Basic word mark search and type "CDS Hooks". My understanding is that It's in progress still.

The language you're proposing here looks good to start; we'll aim to get official advise shortly.

(I don't think you need to mention an Apache license unless we're talking about the source code for the sandbox.)

**Comment by mattvarghese** [comment]
Ok - adding a plain text version also here, since I find that in some places I may be limited to plain text for the attribution.
> <pre><code>CDS Hooks® and the CDS Hooks logo (https://cds-hooks.hl7.org/images/logo-square.png)® are trademarks of HL7 and Boston Children's Hospital, copyrighted and licensed under a Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/) as specified at https://cds-hooks.hl7.org/</code></pre>

For instances where I only use CDS Hooks, and not the Logo, I'll use this likewise
Formatted:
><b>CDS Hooks&reg;</b> is a trademarks of <b>HL7</b> and <b>Boston Children's Hospital</b>, copyrighted and licensed under a Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/) as specified at https://cds-hooks.hl7.org/

PlainText:

> <pre><code>CDS Hooks® is a trademarks of HL7 and Boston Children's Hospital, copyrighted and licensed under a Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/) as specified at https://cds-hooks.hl7.org/</pre></code>

**Comment by mattvarghese** [comment]
Also, @jmandel, do you have an estimate of how long this will take to finalize? Are we talking a few days? Or are we talking many months?

**Comment by kpshek** [comment]
We definitely need to be explicit in how the logo is licensed and how it can be used. IANAL, but think it would be good to be consistent in how the FHIR and SMART logos are licensed and can be used.

**Comment by jmandel** [comment]
I don't have an estimate; this is something that needs attention from Boston Children's Hospital counsel (I've reached out).

**Comment by jmandel** [comment]
Beginning to address this in https://github.com/cds-hooks/docs/pull/479 (though there is still work to be done in posting official guidance to smarthealthit.org).

**Comment by isaacvetter** [comment]
Hey @mattvarghese , @jmandel - this issue is now resolved with the content on https://smarthealthit.org/cds-hooks-logo/ and the link on https://cds-hooks.org/logo-use/
