### ISSUE TITLE
Inform a CDS Service its decision support should evaluate it's logic at the given datetime

### ISSUE THREAD

**Issue by kpshek** [cds-hooks/docs#50]
In discussion with @brynrhodes and @isaacvetter regarding aligning Clinical Reasoning and CDS Hooks, one of the topics of discussion was around how Clinical Reasoning allows the EHR to include to the CDS service that it should evaluate it's rules at the specified date/time (`evaluteAt` field). This is used for testing or debugging purposes in Clinical Reasoning.

[rfc7089](https://tools.ietf.org/html/rfc7089#section-2.1.1) defines an `Accept-Datetime` HTTP request header to accomplish this same functional goal. In our case, the EHR would send the `Accept-Datetime` HTTP header in the CDS Service request. The CDS Service would evaluate it's decision support logic as of this given datetime.

Per rfc7089, the CDS Service should also return a response header in this scenario with the `Memento-Datetime` HTTP header set to the datetime the decision support was evaluated at.

It is worth mentioning that in order for the decision support rules to be evaluated at an arbitrary datetime, all services and systems used by the CDS Service must be capable of supporting this concept. This includes both the EHR and FHIR server who must be capable of querying FHIR resources at the given datetime.

**Comment by des4900** [comment]
Another use case for evaluating CDS at a specified date-time is for scheduling services and providers and patients for routine interventions or analysis in the future.  For example, it can be used to determine that a patient needs certain lab work done in advance of an upcoming appointment, or simply that a patient needs to have a preventative appointment, and should be contacted.

**Comment by euvitudo** [comment]
I would prefer `evaluateAt` (or some variation) to be part of the payload.

I would prefer not to have to implement RFC 7089 on the backend.  Some reasons include:

- RFC 7089 is not an official standard.
- GET and HEAD are mentioned in the RFC, but POST is not, and in fact, in the context of the RFC, POST doesn't make sense, as the RFC is all about obtaining past versions of Web documents.
- Implementing this would be overly complex.

Finally, it seems relevant that a CDS Service should indicate what features it implements (much like the CapabilityStatement).  If it cannot support an `evaluateAt` (or variation), then it simply doesn't include that in its service metadata.  `prefetch` is already stating what it would prefer to have included in the request payload.

**Comment by yashaskram** [comment]
I might be completedly off base here with my understanding of this ask.

- Is this a scenarios where CDS service provider is expected to queue up the hook request until evaluateAt ?
- How would CDS Hook service get the FHIR data at evaluateAt time? Is the expectation that the access token would live until evaluateAt + x ? 
- And also how does EHR handle card response when EHR user close the patient chart before evaluateAt?

In general  I agree with @euvitudo  that it should part of the payload (from implementation efforts perspective) if we plan to have this supported as part of CDS Hook spec.

**Comment by kpshek** [comment]
@euvitudo & @yashaskram - Thanks for your thoughts / comments on this issue!

> @euvitudo: RFC 7089 is not an official standard.

My original intention of suggesting RFC 7089 was to leverage work that had already been done for a similar concept. I realize it isn't a standard but neither is many other concepts we're designing. :-)

However, I given that RFC 7089 doesn't call out POST requests as supporting `Accept-Datetime` in addition to that we're only using a small portion of this RFC, I agree that we shouldn't reference RFC 7089 or use the name `Accept-Datetime`.

> @euvitudo: Implementing this would be overly complex

How would a request header to the CDS Service be overly complex to read/handle? Whether it is a request header or a POST body parameter, it seems just as easy to implement IMHO. For instance, in Rails, we're talking about the difference between:

```ruby
# request header
request.headers['Evaluate-At-Datetime']

# POST body param
params['Evaluate-At-Datetime']
```

In Java, reading a request header is also easy:

```java
// request is a javax.servlet.http.HttpServletRequest
request.getHeader("Evaluate-At-Datetime");

// Or, if we're dealing with a connection of type java.net.URLConnection
connection.getHeaderFields().get("Evaluate-At-Datetime");
```

> @euvitudo: Finally, it seems relevant that a CDS Service should indicate what features it implements (much like the CapabilityStatement). If it cannot support an evaluateAt (or variation), then it simply doesn't include that in its service metadata. prefetch is already stating what it would prefer to have included in the request payload.

Just as important if the CDS Service supports this functionality is that the EHR and more importantly FHIR server can support this functionality. We do not something akin to the CapabilityStatement today. The CDS Service definition in Discovery does describe each CDS Service, but I wouldn't equate it to a CapabilityStatement. I'd prefer to avoid venturing into that domain for the time being.

@yashaskram - This use case originally came from Ken, @brynrhodes, & @euvitudo's team at Univ of Utah where with Clinical Reasoning, they can evaluate CDS at a given point in time. For instance, they can answer questions like "What decision support was shown to user U for patient P last week on May 30, 2017 8:00am"? This is very cool functionality but requires the *entire* system to support this sophisticated date-based querying. Critically, the FHIR server must support these time based queries, none of which are support by production FHIR servers from the major commercial EHR vendors today. The Univ of Utah implementation supports it because they have built this all themselves.

> @yashaskram: In general I agree with @euvitudo that it should part of the payload (from implementation efforts perspective) if we plan to have this supported as part of CDS Hook spec.

I also think it's important to note that this feature is going to be an edge case in that it will not see widespread adoption. I say this because in order for this 'evaluate at' functionality to be supported, the underlying FHIR server must support these types of queries. Currently, I do not know of any EHR vendor that has implemented this functionality. This is why I would prefer keeping this out of the CDS Service request body as we would be defining a new request field for something that is not widely implemented. This is why the request header was appealing to me.

@euvitudo - What about this revised proposal?

`Evaluate-At-Timestamp` - A request header specified by the EHR In the CDS Service request to indicate the timestamp used by the CDS Service as the notion of 'now'. If the CDS Service is able to honor this timestamp, its response back to the EHR must include the `Evaluate-At-Timestamp` header with the same timestamp value. The timestamp value is an ISO 8601 UTC timestamp using the format YYYY-MM-DDTHH:MM:SSZ

**Comment by euvitudo** [comment]
@kpshek:

> > @euvitudo: RFC 7089 is not an official standard.

> My original intention of suggesting RFC 7089 was to leverage work that had already been done for a similar concept. I realize it isn't a standard but neither is many other concepts we're designing. :-)

So you don't intend for cds-hooks to become a standard?

> > @euvitudo: Implementing this would be overly complex

> How would a request header to the CDS Service be overly complex to read/handle? Whether it is a request header or a POST body parameter, it seems just as easy to implement IMHO. For instance, in Rails, we're talking about the difference between:

You take my comment out of context.  What I said was a bullet point to implementing RFC 7089.

> > @euvitudo: Finally, it seems relevant that a CDS Service should indicate what features it implements (much like the CapabilityStatement). If it cannot support an evaluateAt (or variation), then it simply doesn't include that in its service metadata. prefetch is already stating what it would prefer to have included in the request payload.

> Just as important if the CDS Service supports this functionality is that the EHR and more importantly FHIR server can support this functionality. We do not something akin to the CapabilityStatement today. The CDS Service definition in Discovery does describe each CDS Service, but I wouldn't equate it to a CapabilityStatement. I'd prefer to avoid venturing into that domain for the time being.

In my mind the CDS Hooks Discovery mechanism is indeed equivalent to a CapabilityStatement.  Also in my mind is the fact there's no way around defining it as such.

> > @yashaskram: In general I agree with @euvitudo that it should part of the payload (from implementation efforts perspective) if we plan to have this supported as part of CDS Hook spec.

> I also think it's important to note that this feature is going to be an edge case in that it will not see widespread adoption. I say this because in order for this 'evaluate at' functionality to be supported, the underlying FHIR server must support these types of queries. Currently, I do not know of any EHR vendor that has implemented this functionality. This is why I would prefer keeping this out of the CDS Service request body as we would be defining a new request field for something that is not widely implemented. This is why the request header was appealing to me.

I honestly see this as no different than supporting the request header for this use case.

At any rate, if you insist on a header, naming the header Evaluate-At-DateTime would be my preference; requiring it to conform to ISO 8601 would be fine; requiring UTC is unreasonable, as ISO 8601 supports time zones.  Any decent Date-Time library should be able to support this.

**Comment by kpshek** [comment]
> So you don't intend for cds-hooks to become a standard?

Of course I want CDS Hooks to be a standard. 😄 Sorry, my original comment wasn't clear. What I intended to get across was that it didn't matter to me that RFC 7089 wasn't a standard because most of everything that we're creating also isn't a standard right now. At any rate, this is moot because I agree with you that using RFC 7089 is a good choice. 😜 

> You take my comment out of context. What I said was a bullet point to implementing RFC 7089.

I'm sorry, I didn't mean to take your comment out of context. I see now that you were probably referring to the complexity of implementing all of RFC 7089. I completely agree it is far more involved and contains more than the small piece I was proposing we leverage.

> In my mind the CDS Hooks Discovery mechanism is indeed equivalent to a CapabilityStatement. Also in my mind is the fact there's no way around defining it as such.

I agree our Discovery endpoint is closely related to the CapabilityStatement in FHIR. I'm just trying to keep it as simple as possible for as long as possible. 😄 

> requiring UTC is unreasonable, as ISO 8601 supports time zones. Any decent Date-Time library should be able to support this

ISO 8601 support time zone *offsets* but this is a different concept than timezones. Timezone offsets have not concept of DST whereas timezones do. For instance, given an ISO 8601 date of `2005-10-30T02:00:00-05:00`, what is the correct UTC value? Here is Java code which illustrates this issue:

```Java
import org.joda.time.DateTimeZone;
import org.joda.time.Instant;

Instant i = new Instant("2005-10-30T02:00:00-05:00");
System.out.println(i); // 2005-10-30T07:00:00.000Z
System.out.println(i.toDateTime(DateTimeZone.UTC)); // 2005-10-30T07:00:00.000Z
System.out.println(i.toDateTime(DateTimeZone.forOffsetHours(-5))); // 2005-10-30T02:00:00.000-05:00
System.out.println(i.toDateTime(DateTimeZone.forID("America/Chicago"))); // 2005-10-30T01:00:00.000-06:00
System.out.println(i.toDateTime(DateTimeZone.forID("America/Indiana/Indianapolis"))); // 2005-10-30T02:00:00.000-05:00
```

So, if we want to support time zones we need to use an ISO 8601 timestamp *and* a time zone. However, if we align on UTC, we will not have this issue.

**Comment by euvitudo** [comment]
> > So you don't intend for cds-hooks to become a standard?
> Of course I want CDS Hooks to be a standard. 😄 Sorry, my original comment wasn't clear. What I intended to get across was that it didn't matter to me that RFC 7089 wasn't a standard because most of everything that we're creating also isn't a standard right now. At any rate, this is moot because I agree with you that using RFC 7089 is a good choice. 😜

That's the thing--I don't agree that RFC 7089 itself is a good choice.

> > In my mind the CDS Hooks Discovery mechanism is indeed equivalent to a CapabilityStatement. Also in my mind is the fact there's no way around defining it as such.

> I agree our Discovery endpoint is closely related to the CapabilityStatement in FHIR. I'm just trying to keep it as simple as possible for as long as possible. 😄

I think you misunderstand again--I don't think the Discovery endpoint should be a CapabilityStatement, but it should express what the service is capable of and is meant to do.  Hence the intent of the Discovery endpoint is similar to the CapabilityStatement.

> So, if we want to support time zones we need to use an ISO 8601 timestamp and a time zone. However, if we align on UTC, we will not have this issue.

Fair enough.  You are correct--something I guess I've forgotten.

**Comment by euvitudo** [comment]
To clarify--call the header support something else.  Don't call it RFC 7089.

**Comment by kpshek** [comment]
@euvitudo - We agree, I just had a crucial typo (that's what I get for writing comments at midnight). I agree RFC 7089 is **not** a good choice. I think we're all good on this point. 😄

**Comment by euvitudo** [comment]
@kpshek How would you suggest a CDS Service advertise that it is capable of evaluating at a specified time?

**Comment by alextdejong** [comment]
Even if the CDS Service is capable of doing this, if the FHIR resources used are not capable of this, it still would not work, correct? I am not suggesting it would not be worthwhile for the CDS Services to advertise it; it just does not automatically means it would actually work when calling the CDS service.

**Comment by brynrhodes** [comment]
Can we do this with just a custom header and have it be optional, but systems that don't support it would throw?

**Comment by euvitudo** [comment]
@brynrhodes Any custom headers (header names/keys) that are not understood should be ignored.

For example, if a specified-time header were provided and the system threw an error that it didn't understand the specified-time header, then in reality it does understand it sufficiently to throw the error.  Rather contradictory in my mind.

**Comment by isaacvetter** [comment]
I think that I agree with you, @euvitudo, but is there a simple existing method for the EHR to know that the CDS service didn't understand the header?

**Comment by euvitudo** [comment]
I wouldn't think so.  If it's not an explicit part of the standard, then how would a service even know how to handle the header (or, for the case where, e.g., specified-time is included in the request standard, the data element in the actual request)?

To wit: If it's not part of the standard, then there's no way of knowing.

**Comment by euvitudo** [comment]
I suppose an alternative is to add an element to the response indicating the time at which the CDS evaluation occurred.  It wouldn't necessarily need be tied to a specified-time header, but would need to be part of every response.

**Comment by kpshek** [comment]
After further thought, I don't think this is something we should tackle right now. My main reasoning is that the FHIR server would need to support the ability to retrieve data at a given point in time. FHIR doesn't support this today so even if we added a field to the CDS Hooks API somewhere, it is unclear how the FHIR endpoint would also honor this.

Additionally, while I see there is a place for this use case (primarily for testing), I think it is fairly limited right now (especially since FHIR isn't capable of this today).

I propose we defer this until this is addressed within FHIR. I'd appreciate the thoughts from @brynrhodes and @isaacvetter on this particular issue too.

**Comment by euvitudo** [comment]
@kpshek Could you elaborate why you don't think FHIR has the ability to retrieve data at a given point in time?  Many (all?) of the search operations include the ability to include date constraints (e.g., lt2017-01-01, etc.) that makes this use case feasible.

**Comment by brynrhodes** [comment]
@euvitudo it's not just returning data at a point in time, but returning what the data _was_ at that point in time that is the difficulty. FHIR supports versioning so in theory an engine could do it, but none of the production-track implementations I'm aware of support this functionality.

**Comment by grahamegrieve** [comment]
"What decision support was shown to user U for patient P last week on May 30, 2017 8:00am" - that's an audit functionality that is supportable. "What decision support would have been shown to user U for patient P last week on May 30, 2017 8:00am" - that's tricky, because there's a lot of moving parts that change independently of each other. 

It's correct that FHIR doesn't try to enable this; I've only ever seen one system that could behave like this (it had an insert only database), and even then, it was fragile because changes to configuration intersected with changes to the code, and cross-cut the ability to retrieve old records exactly as they were. And consistent with my experience, no one has asked for it (till now)

**Comment by kpshek** [comment]
Well put @grahamegrieve. This issue wasn't trying to address the auditing capability you referred to. It really was to try and explore the latter use case which as you've confirmed, is not possible today.

**Comment by isaacvetter** [comment]
Hey @euvitudo  - I've started a comment on this thread a few times today, let me know if I can give you a call to talk through this. I want to ensure that your voice and needs are heard and given appropriate weight. 

Perhaps due to the relatively simple, early use-cases for the standard, there isn't much call for this feature. Further, we can't figure out a way to accommodate it without weakening the current, appealingly simple CDS request message. Based upon the above few posts and my knowledge of my own FHIR server and roadmap, there's not widespread support for "point-in-time" FHIR queries. 

For these reasons, I think that it makes sense to defer an _evaluateAt_ feature until at least one of the above statements is no longer true. 

Isaac

**Comment by euvitudo** [comment]
Hey @isaacvetter - given the above, it seems reasonable to defer.

**Comment by kpshek** [comment]
Thanks everyone -- labeling this as deferred for now.

**Comment by kensaku-kawamoto** [comment]
In the interim, we will plan to either (i) create a proprietary extension to support this notion of a specified time or (ii) do that at the level of the decision engine underlying CDS Hooks.  E.g., if we pursue (ii), we can still do what we currently do -- create dozens or hundreds of test cases for a CDS module with static input test data (e.g., a FHIR bundle), have the CDS module evaluate this information at a given specified time, and to verify that the end result/output is as expected in statically defined expectations.  I agree that for real-time/dynamic CDS Hooks usages, the specified time is tricky to get working and may not be worth the effort.  As long as the ability to get consistent evaluation results from a static set of test case data is there, I would be fine.  Also would need to be able to evaluate consistency of behavior that is date/time dependent, e.g., making sure that an after-hours alert (such as "for ECHO outside of business hours, please page XYZ") can be tested at boundary conditions without actually running them at 4:59pm vs 5:00pm on a Monday, on Labor Day, etc.

**Comment by kpshek** [comment]
Thanks @kensaku-kawamoto - please let us know how this goes for you
