### ISSUE TITLE
Patient-view:  context.encounter should be named encounterId

### ISSUE THREAD

**Issue by bvdh** [cds-hooks/docs#501]
The patient-view context holds three fields: userId, patientId and encounter.
As the encounter field also holds an id field, it should be renamed to encounterId in line with the other fields.

**Comment by brynrhodes** [comment]
The current version of the [patient-view hook](https://cds-hooks.org/hooks/patient-view/) does call the encounter field `encounterId`, and I verified that what's included in the STU update content does as well. Where are you seeing the hook context called `encounter`?

**Comment by bvdh** [comment]
Not sure - but that means this issue can be dropped,
