### ISSUE TITLE
`context.userId` is inconsistent and should almost always be `PractitionerRole`

### ISSUE THREAD

**Issue by isaacvetter** [cds-hooks/docs#514]
The PractitonerRole resource identifies a clinical user acting within a specific organization with given credentials, specialties, authorizations and role. 

It seems like the `userId` field in context SHOULD be valued with a PractitionerRole resources, if the hook is fired during a provider-facing workflow. In the case where a PractitionerRole isn't supported (e.g. DSTU2), Practitioner should be sent. 

For patient-facing workflows, userId SHOULD be Patient or, in proxy-scenarios, RelatedPerson.

**Comment by isaacvetter** [comment]
We should update each hook to clarify when Patient/RelatedPerson may be used and that PractitionerRole is appropriate.

**Comment by jmandel** [comment]
Makes sense to allow; can you point me toward the discussion or documentation that leads you to *prefer*?
