### ISSUE TITLE
Should include a clinical scenario for the built-in patient-view and medication-review hooks

### ISSUE THREAD

**Issue by manojhajur** [cds-hooks/docs#54]
Can we include a relevant clinical scenario in the documentation, such that those who are reviewing the Introduction wiki page, or the sandbox demo page (a doc link on the top right of each main page for that hook), then they can see the use of the cds-hooks spec?

ie. 
1) select Rx Review
2) select patient X
3) select problem Y 
4) select med Z
5) review "cards" and select med Z3
6) see final decision

**Comment by kpshek** [comment]
@manojhajur - Thanks for logging this! I reposted this issue against our [sandbox](https://github.com/cds-hooks/sandbox) as cds-hooks/sandbox#39. As such, I'm closing this issue here.
