### ISSUE TITLE
Action.resource documentation

### ISSUE THREAD

**Issue by robs16** [cds-hooks/docs#77]
The recent updates added suggestion.action.resource defined as an object. However the documentation on this is not completely clear: 

> **object**. depending upon the type attribute, new resource(s) or id(s) of resources. For a type of create, the resource attribute contains new FHIR resources to apply within the current activity (e.g. for medication-prescribe, this holds the updated prescription as proposed by the suggestion). **For delete, id(s) of any resources to remove from the current activity (e.g. for the order-review activity, this would provide a way to remove orders from the pending list)**. In activities like medication-prescribe where only one “content” resource is ever relevant, this field may be omitted. For update, existing resources to modify from the current activity (e.g. for the order-review activity, this would provide a way to annotate an order from the pending list with an assessment). This field may be omitted.

Specifically it is unclear how a delete is represented within the context of an object.  It suggests an array rather than an object. Also since this format has defined one action for each create or update, should the delete follow the same paradigm (ie single delete id per action record)?

**Comment by brynrhodes** [comment]
Agreed, the wording should be updated to make clear that the action deals with a single resource. I've submitted PR #107 to address this.

**Comment by kpshek** [comment]
Fix by #107. Thanks @brynrhodes!
