### ISSUE TITLE
State keeping 

### ISSUE THREAD

**Issue by bvdh** [cds-hooks/docs#80]
In the section "CDS Decisions" it is stated that "To return a decision after a user interaction, the CDS service must maintain state associated with the request’s hookInstance; when the EHR invokes the hook for a second time with the same hookInstance, the service can respond with decisions on as well as cards".

To my knowledge this is not the typical behavior when calling webservices. 
Preferably one would have the CDS services stateless and store the state in the EHR application. When it invokes the service, it will pass the state. This prevents a lot of (difficult) bookkeeping in the services (such as determining when how long a state should be maintained).  

**Suggested change:**
Preferably one would have the CDS services stateless and store the state in the EHR application. Can’t we have the CDS Service pass a optional “opaque” state object when it redirects back to the EHR. The EHR then appends this object to the CDS Service request. Thereby passing the state.

**Comment by grahamegrieve** [comment]
For me personally, this would equate to the server making up the identifier for the state, not the client.

**Comment by robs16** [comment]
This state could be very large depending on the needs of the service. The issue of how long it must be maintained is still a problem, just shifted to the EMR. The state definition could also change over time, making updates of the service much more difficult.

**Comment by bvdh** [comment]
From my point of view, the EHR maintains the current session. So it also knows when state is no longer relevant.

**Comment by robs16** [comment]
I see your point for a simple service. As long as statefull is also supported, it works for me. The service provider would have to figure out which model works best for their need.

You would also have to pass the state in both directions for analytic endpoints.

**Comment by kpshek** [comment]
Per discussion at the Sept WGM (Tue Q2), we will defer this issue given that Decisions are not making the pending 1.0 release (TODO: Kevin to add more details on this as an update to the comment)

**Comment by kpshek** [comment]
Thanks for the feedback on decisions, @bvdh.

At the Sept 2017 San Diego Connectathon, the community reached consensus to remove decisions for the 1.0 release (#99) until we obtain more implementer feedback. I think the questions you pose here are further indication that the decisions feature needs quite a bit of further thought, implementation feedback, and documentation.

We will swing back on the decisions feature on a subsequent release. As such, I'm closing this issue with a deferred label.
