### ISSUE TITLE
Support of JSON and/or xml

### ISSUE THREAD

**Issue by bvdh** [cds-hooks/docs#81]
What formatting is supported in REST calls? The specification seems to suggest that JSON is supported. Is xml also supported? 
I suggest to state that the CDS Service MUST support JSON, and MAY support xml. The EHR MUST support JSON as well as xml.
Also provide references to the JSON specification (rfc7159) and xml specifications.

**Comment by olbrich** [comment]
I don't know that the specification really should care about what format is used for interchange, but pragmatically I would expect any such service would provide at least XML *or* JSON.

**Comment by kpshek** [comment]
CDS Hooks only defines JSON as the data format -- everyone MUST support JSON (so we have that question answered).

I personally do not want to define support for XML in CDS Hooks as I don't see much value in doing so. JSON is pervasive and has proven to be very popular and well supported by everyone. Also defining optional support for XML will further increase our complexity (or at the very least, surface area).

Is XML a must have for you @bvdh?

**Comment by grahamegrieve** [comment]
you might say that the CDS <--> FHIR Server interface could make use of XML if the EHR capability statement allows for it, but introducing an XML format in the EHR <--> CDS interface seems like a lot of work for very little outcome

**Comment by bvdh** [comment]
My main concern is that the spec is a bit vague in specifying what is mandatory. If the only thing that is supported is JSON. That is ok for me. But please state it explicitly.

**Comment by kpshek** [comment]
Per discussion at the Sept WGM (Tue Q2), we will update the spec to explicitly state that JSON (and only JSON) MUST be supported by both the EHR and CDS Services.
