### ISSUE TITLE
Some questions related to Decisions

### ISSUE THREAD

**Issue by bvdh** [cds-hooks/docs#96]
The spec states that a Decision contains a list of id(s) of resource(s) that the EHR should create/remove from the current activity. 
Action allow removal or update of the resources in the current activity.

I'm a bit puzzled how this is supposed to work. Some clarification, e.g. an example, would be appreciated.

Some questions related to this topic:
1. What is the "Current Activity"?

2. How does the service know what objects are present in the current activity? Is the scope of a Action or Decision limited to the the content of the hook specific context?

2. As the decision is passing id's. Is it the responsibility of the CDS Service to persist the related changes in the FHIR repository, so that the EHR can retrieve them and add to the current activity?

3. Can we assume that all interaction on the EHR screen has been made persistent in the FHIR repository so that they are accessible by the CDS Service?

**Comment by kpshek** [comment]
Thanks for the feedback and questions @bvdh.

At the Sept 2017 San Diego Connectathon, the community reached consensus to remove decisions for the 1.0 release (#99) until we obtain more implementer feedback. I think the questions you pose here are further indication that the decisions feature needs quite a bit of further thought, implementation feedback, and documentation.

We will swing back on the decisions feature on a subsequent release. As such, I'm closing this issue with a _deferred_ label.
